// let server_addr="http://app.qiyu.live.com:8088";
let server_addr="http://localhost:8088";

let apiUrl = "/live/api";
let sendSmsUrl = server_addr + apiUrl + "/userLogin/sendLoginCode";
let loginUrl = server_addr + apiUrl + "/userLogin/login";
let homePageUrl = server_addr + apiUrl + "/home/initPage";
let startLiving = server_addr + apiUrl + "/living/startingLiving";
let closeLiving = server_addr + apiUrl + "/living/closeLiving";
let anchorConfigUrl = server_addr + apiUrl + "/living/anchorConfig";
let listLivingRoomUrl = server_addr + apiUrl +"/living/list";
let getImConfigUrl = server_addr + apiUrl + "/im/getImConfig";
let listGiftConfigUrl = server_addr + apiUrl + "/gift/listGift";
let sendGiftUrl = server_addr + apiUrl + "/gift/send";
let payProductsUrl = server_addr + apiUrl + "/bank/products";
let payProductUrl = server_addr + apiUrl + "/bank/payProduct";
let onlinePkUrl = server_addr + apiUrl + "/living/onlinePK";
let prepareRedPacketUrl = server_addr + apiUrl + "/living/prepareRedPacket";
let startRedPacketUrl = server_addr + apiUrl + "/living/startRedPacket";
let getRedPacketUrl = server_addr + apiUrl + "/living/getRedPacket";
let queryShopInfoUrl = server_addr + apiUrl + "/shop/listSkuInfo";
let queryShopDetailInfoUrl = server_addr + apiUrl + "/shop/detail";
let addShopCarUrl = server_addr + apiUrl + "/shop/addCar";
let getCarInfoUrl = server_addr + apiUrl + "/shop/getCarInfo";
let removeFromCarUrl = server_addr + apiUrl + "/shop/removeFromCar"
let createPrepareOrderInfoUrl = server_addr + apiUrl + "/shop/prepareOrder";
let payNowUrl = server_addr + apiUrl +"/shop/payNow";