spring:
  application:
    name: qiyu-live-bank-provider
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 200
    driver-class-name: com.mysql.cj.jdbc.Driver
    #访问主库
    url: jdbc:mysql://cloud.db:8808/qiyu_live_bank?useUnicode=true&characterEncoding=utf8
    username: root
    password: qiyu

  data:
    redis:
      port: 8801
      host: cloud.db
      password: qiyu
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    #docker启动的时候，注入host的配置
    address: nacos://qiyu.nacos.com:8848?namespace=qiyu-live-test&&username=qiyu&&password=qiyu
  protocol:
    name: dubbo
    port: 9096
    threadpool: fixed
    dispatcher: execution
    threads: 500
    accepts: 500

qiyu:
  rmq:
    producer:
      nameSrv: qiyu.rmq.com:9876
      groupName: ${spring.application.name}
      applicationName: ${spring.application.name}
      sendMsgTimeout: 3000
      retryTimes: 2