spring:
  application:
    name: qiyu-live-msg-provider
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 200
    driver-class-name: com.mysql.cj.jdbc.Driver
    #访问主库
    url: jdbc:mysql://cloud.msg.db:8808/qiyu_live_msg?useUnicode=true&characterEncoding=utf8
    username: qiyu
    password: qiyu
  data:
    redis:
      port: 8801
      host: cloud.db
      password: qiyu
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10

qiyu:
  sms:
    ccp:
      smsServerIp: app.cloopen.com
      port: 8883
      accountSId: [容联云上的accountSID]
      accountToken: [容联云上的Token]
      appId: [容联云上的appId]
      templateId: 1
      testPhone: 13510647925

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://qiyu.nacos.com:8848?namespace=qiyu-live-test&&username=qiyu&&password=qiyu
  protocol:
    name: dubbo
    port: 9090